6дек23

# Матрицы. Продолжение

* Как решать простые матричные уравнения?
* Как связаны между собой матричные и линейные уравнения?
* Как это закодить?

## Матричные уравнения

Я обленился, так что просто кину ссылку на [эту страницу](https://thecode.media/matrix-equation/), если ты пропустил урок или просто хочешь вспомнить теорию – тебе туда.


In [1]:
# уравнение вида A * X = B

import numpy as np
A = np.array([[3, 7], 
              [2, 8]])

B = np.array([[4, 8], 
              [6, 2]])

A, B

(array([[3, 7],
        [2, 8]]),
 array([[4, 8],
        [6, 2]]))

Две матрицы есть. Из материала теории знаем, что $X = A^{-1} \cdot B$. Так что находим $A^{-1} = \frac{1}{|A|} \cdot A^T_{ij}$

In [2]:
# определитель
det_A = np.linalg.det(A)
det_A

10.000000000000002

In [3]:
# транспонированная матрица миноров

M = A.copy()

for i in (0, 1):
    for j in (0, 1):
        M[i][j] = (-1) ** (i + j) * A[(i + 1) % 2][(j + 1) % 2]
        
M = M.T
M

array([[ 8, -7],
       [-2,  3]])

In [4]:
# обратная матрицы
A_inv = (1 / det_A) * M
A_inv

array([[ 0.8, -0.7],
       [-0.2,  0.3]])

In [5]:
# проверим по свойству
A_inv.dot(A)

array([[1., 0.],
       [0., 1.]])

In [6]:
# находим Х
X = A_inv.dot(B)
X

array([[-1.,  5.],
       [ 1., -1.]])

In [7]:
# проверка A * X == B
A.dot(X)

array([[4., 8.],
       [6., 2.]])

## Это все имеет значение,
потому что помогает решать системы линейных уравнений.
$$
\begin{equation*}
 \begin{cases}
   3 x + 2 y - z = 8 
   \\
   x - y + z = -2 
   \\
   2 x - 3 y - 5 z = 1 
 \end{cases}
\end{equation*}
$$
Эту систему можно представить, как
$A \cdot X = B$, где

In [8]:
A = np.array([[3,  2, -1],
              [1, -1,  1],
              [2, -3, -5]])

B = np.array([[ 8],
              [-2],
              [ 1]])

# X = [[x], [y], [z]]

# определитель
det_A = np.linalg.det(A)

import lib.l9 as l9 
# эта функция возвращает определитель минора в матрице по координатам
# тестировал только на матрице 3х3

A_inv = np.array([[l9.f(A, i, j) * (-1) ** (i + j) for j in range(len(A[i]))] for i in range(len(A))])
A_inv = (1 / det_A) * A_inv.T
A_inv

# получившаяся обратная матрица

array([[ 0.20512821,  0.33333333,  0.02564103],
       [ 0.17948718, -0.33333333, -0.1025641 ],
       [-0.02564103,  0.33333333, -0.12820513]])

In [9]:
# проверка A_inv * A == 1
# она очень старается выдать единичную матрицу, а получается вот такое
# все числа кроме главной диагонали настолько близки к нулю, что на самом деле это все-таки 0

A_inv.dot(A)

array([[ 1.00000000e+00, -1.38777878e-17,  1.38777878e-17],
       [-5.55111512e-17,  1.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00,  5.55111512e-17,  1.00000000e+00]])

In [10]:
# ответ

X = A_inv.dot(B)
X

array([[ 1.],
       [ 2.],
       [-1.]])

In [11]:
# проверка A * X == B

A.dot(X)

array([[ 8.],
       [-2.],
       [ 1.]])

### Уточню, что такой метод позволяет найти корень только в том случае, если он один. Если корней нет или их несколько – определитель будет равен нулю и нам придется делить $\frac{1}{0}$, что все-таки проблематично.

---
## Задачи для самостоятельного выполнения
Дедлайн 11дек23 23:59.

При написании кода нельзя пользоваться **никакими** сторонними библиотеками.

## Вариант 1
Для обеих Маш, Марго, Кристины, Лизы и Златы. А также, может быть когда-нибудь, для Дани и (ну, вдруг) для Гриши.
1. **Найти меня**, получить от меня **матричное уравнение** (того же вида, что представлен в материале урока и при мне же **решить его**.
2. **Написать функцию.** Функция **принимает на вход** два списка (A, B), они же матрицы размера (3, 3), **выдает** список X, корень матричного уравнения A * X = B, если он один, или выводит ошибку, если уравнение не имеет корней или имеет больше одного корня.

## Вариант 2
Для обеих Арин, Иры, Ульяны, Вардана и Веры.
1. **Найти меня**, получить от меня **матричное уравнение** (того же вида, что представлен в материале урока и при мне же **решить его**.
2. **Написать функцию.** Функция **принимает на вход** два списка (A, B), они же матрицы произвольного размера, **выдает** список X, корень матричного уравнения A * X = B, если он один, или выводит ошибку, если уравнение не имеет корней или имеет больше одного корня.

